import javax.swing.JPanel;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import java.awt.Font;
import javax.swing.border.TitledBorder;
import javax.swing.JTextArea;
import java.awt.Dimension;
import javax.swing.border.BevelBorder;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JScrollPane;
import java.awt.Color;
import javax.swing.JCheckBox;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Emails extends JPanel{
    JPanel p1;

    public Emails(){
        setLayout(null);
        setPreferredSize(new Dimension(450,480));
        setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        setBackground(Color.WHITE);
        TitledBorder border = BorderFactory.createTitledBorder("SMTP server");
        border.setTitleFont(new Font("Arial",Font.PLAIN,14));
        border.setBorder(BorderFactory.createLineBorder(new Color(150,150,150), 1));
        JPanel p1 = new JPanel();
        p1.setBackground(Color.WHITE);
        p1.setBorder(border);         
        p1.setLayout(null);    
        p1.setBounds(80,5,350,68);
        JLabel ipname = new JLabel("IP/Name: ");
        ipname.setBounds(60,15,60,20);
        p1.add(ipname);
        JTextField tipname = new JTextField();
        tipname.setBounds(125,15,150,20);
        p1.add(tipname);
        JLabel port = new JLabel("Port: ");
        port.setBounds(60,40,60,20);
        p1.add(port);
        JTextField tport = new JTextField();
        tport.setBounds(125,40,150,20);
        p1.add(tport);
        add(p1);
        border = BorderFactory.createTitledBorder("Authentication");
        border.setTitleFont(new Font("Arial",Font.PLAIN,14));
        border.setBorder(BorderFactory.createLineBorder(new Color(150,150,150), 1));
        JPanel p2 = new JPanel();
        p2.setBackground(Color.WHITE);
        p2.setBorder(border);         
        p2.setLayout(null);    
        p2.setBounds(80,73,350,93);
        JLabel user = new JLabel("User: ");
        user.setBounds(60,15,60,20);
        p2.add(user);
        JTextField tuser = new JTextField();
        tuser.setBounds(125,15,150,20);
        p2.add(tuser);
        JLabel pass = new JLabel("Password: ");
        pass.setBounds(60,40,80,20);
        p2.add(pass);
        JTextField tpass = new JTextField();
        tpass.setBounds(125,40,150,20);
        p2.add(tpass);
        JLabel from = new JLabel("From: ");
        from.setBounds(60,65,60,20);
        p2.add(from);
        JTextField tfrom = new JTextField();
        tfrom.setBounds(125,65,150,20);
        p2.add(tfrom);
        add(p2);
        border = BorderFactory.createTitledBorder("Email List");
        border.setTitleFont(new Font("Arial",Font.PLAIN,14));
        border.setBorder(BorderFactory.createLineBorder(new Color(150,150,150), 1));
        JPanel p3 = new JPanel();
        p3.setBackground(Color.WHITE);
        p3.setBorder(border);         
        p3.setLayout(null);    
        p3.setBounds(80,170,350,68);
        JTextArea emails = new JTextArea();
        emails.setLineWrap(true);
        emails.setWrapStyleWord(true);
        JScrollPane scroll = new JScrollPane(emails);
        scroll.setBorder(null);
        scroll.setBounds(5,15,336,45);
        p3.add(scroll);        
        add(p3);
        border = BorderFactory.createTitledBorder("Message");
        border.setTitleFont(new Font("Arial",Font.PLAIN,14));
        border.setBorder(BorderFactory.createLineBorder(new Color(150,150,150), 1));
        JPanel p4 = new JPanel();
        p4.setBackground(Color.WHITE);
        p4.setBorder(border);         
        p4.setLayout(null);    
        p4.setBounds(80,240,350,108);
        JTextArea message = new JTextArea();
        message.setLineWrap(true);
        message.setWrapStyleWord(true);
        JScrollPane scroll2 = new JScrollPane(message);
        scroll2.setBorder(null);
        scroll2.setBounds(5,15,336,85);
        p4.add(scroll2);        
        add(p4);
        final JLabel enable = new JLabel("Disabled");
        enable.setBounds(360,350,60,20);
        add(enable);
        final JCheckBox check = new JCheckBox();
        check.setBounds(412,350,20,20);
        check.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ev){
                if(check.isSelected())enable.setText("Enabled");
                else enable.setText("Disabled");}});
        add(check);}}