import javax.swing.JPanel;
// import org.jfree.chart.ChartFactory;
// import org.jfree.chart.ChartPanel;
// import org.jfree.chart.JFreeChart;
// import org.jfree.data.general.DefaultPieDataset;
// import org.jfree.data.general.PieDataset;
// import org.jfree.util.Rotation;
// import org.jfree.chart.plot.PlotOrientation;
// import org.jfree.data.category.CategoryDataset;
// import org.jfree.data.category.DefaultCategoryDataset;
// import org.jfree.data.xy.XYDataset;
// import org.jfree.data.xy.XYSeriesCollection;
// import org.jfree.data.xy.XYSeries;
// import org.jfree.data.xy.DefaultXYDataset;
// import org.jfree.data.xy.XYBarDataset;
// import org.jfree.chart.plot.XYPlot;
// import org.jfree.chart.axis.NumberAxis;
// import org.jfree.data.xy.IntervalXYDataset;
// import org.jfree.chart.ChartMouseListener;
// import org.jfree.chart.ChartMouseEvent;
import java.awt.GradientPaint;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Random;
import javax.swing.JScrollPane;
import javax.swing.JScrollBar;
import java.awt.event.MouseEvent;
// import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import java.awt.Graphics2D;
// import org.jfree.chart.renderer.xy.XYBarRenderer;
import java.awt.geom.RectangularShape;
// import org.jfree.ui.RectangleEdge;
// import org.jfree.ui.StandardGradientPaintTransformer;
// import org.jfree.ui.GradientPaintTransformType;
// import org.jfree.data.general.DefaultPieDataset;
// import org.jfree.chart.renderer.xy.StandardXYBarPainter;
// import org.jfree.ui.RectangleInsets;
// import org.jfree.chart.plot.PiePlot;
// import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import java.awt.Font;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.JScrollPane;
import java.awt.Toolkit;

public class Panel3 extends JPanel{
    private static final long serialVersionUID = 1L;
    public JTabbedPane pane;
    public JScrollPane panel,panel4,panel2,panel5;
    //public Summary sumary;
    //public History history;
    //public Details details;
    public Browser browser;
    
    public Panel3(){
//         System.out.println("Started Panel3 initialization: "+System.currentTimeMillis());
        Repository.intro.text = "Started Details interface initialization";
        Repository.intro.percent+=0.035;
        Repository.intro.repaint();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLayout(null);
        pane = new JTabbedPane();
        pane.setBounds(5, 5, (int)screenSize.getWidth()-65,630);
//         sumary = new Summary();
//         details = new Details();
//         Delta delta = new Delta();
//         history = new History();
         browser = new Browser();
//         panel = new JScrollPane(sumary);
//         pane.add("Summary",panel);
//         panel2 = new JScrollPane(details);
//         pane.add("Details",panel2);
//         pane.add("Delta",delta);
//         panel4 = new JScrollPane(history);
//         pane.add("History",panel4);
        panel5 = new JScrollPane(browser.displayEditorPane);
        pane.add("Browser",panel5);       
        add(pane);
//         System.out.println("Finished Panel3 initialization: "+System.currentTimeMillis());
        Repository.intro.text = "Finished Details interface initialization";
        Repository.intro.percent+=0.035;
        Repository.intro.repaint();}}